package com.webonise.vehicleDesign;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'deep' at '14/9/16 5:17 PM' with Gradle 2.14
 *
 * @author webonise, @date 14/9/16 5:17 PM
 */
public class Ferrari implements ICar{

    int yearOfMaunfacture;
    String engine;
    int noOfTyres;

    Ferrari(){
        yearOfMaunfacture=2005;
        engine="abc";
        noOfTyres=4;
    }


    @Override
    public boolean hasAirbags() {
        return true;

    }

    @Override
    public boolean hasRoof() {
       return true;

    }

    @Override
    public void hasWheels() {
        System.out.println("Ferrari has "+ noOfTyres + " wheels");

    }

    @Override
    public void hasEngine() {
        System.out.println("Ferrari has " + engine + " engine");


    }
}
